### PR TITLE
Added a init with coder to load the textfield in storyboards or xibs

### PR DESCRIPTION
**Pull request by LightMan**
Added an initWithCoder func, in order to use FormTextField in storyboards or xibs
Added a common init func, used by initWithFrame and initWithCoder
Added a rest fun to clear the text and appearance, for example, removes the red background color if the textfield is not valid

### CODE REVIEW

**Comment by 3lvis** [comment]
@LightMan Thanks David! :tada:

**Comment by LightMan** [comment]
De nada 👍
I have downloaded the pod into my laptop, but it still downloads the previous version of FormTextFied, do you need to update the podspec file to a higher version? There is something that I am missing...

**Comment by 3lvis** [comment]
@LightMan I'll make sure to do an update tomorrow, I totally forgot. Thanks for letting me know!

**Comment by 3lvis** [comment]
Released on 0.9.4 🎉 

https://github.com/3lvis/FormTextField/releases/tag/0.9.4

Thanks again 😊

**Pull request merged**
